### ISSUE TITLE
`appcompat` library can be removed

### ISSUE THREAD

**Issue by CrazyBoyFeng** [h6ah4i/android-numberpickerprefcompat#4]
This project does not use `androidx.appcompat`.
And the `androidx.preference` dependency and `NumberPickerCompat` projects already contain `androidx.appcompat` (don't forget to update the `NumberPickerCompat`'s dependency), so you can safely remove it. 
This way you don't have to manage a duplicate dependency in two library projects.
And after removal, the package size will be reduced.
https://github.com/h6ah4i/android-numberpickerprefcompat/blob/adf2111e3101721d219c52f70702ddec372abcc3/library/build.gradle#L40

**Comment by h6ah4i** [comment]
Thanks. I'll remove that later.

**Comment by CrazyBoyFeng** [comment]
Another suggestion: replace `implementation 'dependency'` with `api 'dependency'`, so that projects using the `numberpickerprefcompat` library do not need to import `preferencecompat` and `numberpickercompat` again when they use them.
The same can be done for `numberpickercompat`. This way, when a project using `numberpickercompat` uses `appcompat`, it does not need to import it again.

**Comment by h6ah4i** [comment]
:tada:  Fixed in [v1.2.1](https://github.com/h6ah4i/android-numberpickerprefcompat/blob/1.2.1/RELEASE-NOTES.md#121).

**Comment by h6ah4i** [comment]
> Another suggestion: replace `implementation 'dependency'` with `api 'dependency'`, so that projects using the `numberpickerprefcompat` library do not need to import `preferencecompat` and `numberpickercompat` again when they use them.
> The same can be done for `numberpickercompat`. This way, when a project using `numberpickercompat` uses `appcompat`, it does not need to import it again.

True, that seems a good improvement :+1:
