### ISSUE TITLE
Default value not honored at first launch

### ISSUE THREAD

**Issue by rmtheis** [h6ah4i/android-numberpickerprefcompat#5]
On a fresh install of my app, my preference value is set to minValue instead of defaultValue. Here's my code:

        <com.h6ah4i.android.preference.NumberPickerPreferenceCompat
            android:defaultValue="10"
            android:key="@string/key"
            android:title="@string/title"
            app:nppc_maxValue="180"
            app:nppc_minValue="2"
            app:nppc_unitText="days"
            app:nppc_wrapSelectorWheel="false" />

When I launch the app, the default value is 2 when I was expecting it to be 10. (By default value, I mean the value initially selected in the dialog, and the value shown in the summary text when using `summaryProvider`.)

Otherwise this is a useful and cool project.

**Comment by h6ah4i** [comment]
Thanks for the issue report. I'll take a look 👀

**Comment by h6ah4i** [comment]
:tada:  Fixed in [v1.2.1](https://github.com/h6ah4i/android-numberpickerprefcompat/blob/1.2.1/RELEASE-NOTES.md#121).

**Comment by rmtheis** [comment]
Thank you for fixing this! I can confirm this change fixes the issue.
